### ISSUE TITLE
Can't install your package

### ISSUE THREAD

**Issue by privefl** [data-steve/googleformr#6]
```
pacman::p_load_gh("data-steve/googleformr")
* installing *source* package 'googleformr' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called 'selectr'
Error : unable to load R code in package 'googleformr'
ERROR: lazy loading failed for package 'googleformr'
* removing 'C:/Users/Florian/Documents/R/win-library/3.3/googleformr'
Error : Command failed (1)
Warning message:
In pacman::p_load_gh("data-steve/googleformr") : 
Failed to install/load:
data-steve/googleformr
```

Using `install.packages("selectr")` and then `pacman::p_load_gh("data-steve/googleformr")` again seems to solve the problem.

**Comment by data-steve** [comment]
Florian,

Thanks for info and sorry for the inconvenience.

This is actually a known issue with the pacman package that it doesn’t install dependencies automatically: https://github.com/trinker/pacman/issues/75 <https://github.com/trinker/pacman/issues/75>

I’ve chatted with the pacman developer and he’s planning on fixing it this week.

~ Steve

Sent via telepathy

**Comment by privefl** [comment]
No problem, it was easy to fix.
Note that it doesn't work with `devtools::install_github("data-steve/googleformr")` either (same error).

**Comment by data-steve** [comment]
sure, default on devtools is also not to auto-install dependencies. Just set dependencies sub option to TRUE: i.e., `devtools::install_github("data-steve/googleformr", dependencies = T)`

~ Steve

Sent via telepathy

**Comment by data-steve** [comment]
I’ll update my README to this install instruction, thanks again.

~ Steve

Sent via telepathy
